author: Michel Lutz & Marcos Lacerda
author_url: https://twitter.com/michel_lutz
github_url: https://github.com/micheltlutz/MLSwiperCards
root_url: https://micheltlutz.github.io/MLSwiperCards/
module: MLSwiperCards
output: docs
theme: fullwidth
xcodebuild_arguments: [-workspace, 'MLSwiperCards.xcworkspace', -scheme, 'MLSwiperCards-iOS']
